'use strict'

var _ = require('lodash')

// Timestamps are dynamically generated by the Event constructor, so we need to replace
// them with something known to validate generated Cypher queries
function fixTime (query) {
    const time_regexp = new RegExp ('[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}T[0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}-[0-9]{1,2}:[0-9]{1,2}', 'g')
    return (_.replace (query, time_regexp, '2016-01-01T00:00:00-04:00'))
}

module.exports.fixTime = fixTime
